import sharp from 'sharp';
import {testBackend} from './http-adapter.mjs';import {chromium} from 'playwright';import {spawn} from 'node:child_process';import {createRequire} from 'node:module';import fs from 'node:fs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const require=createRequire(import.meta.url),ts=require('typescript'),Module=require('module');
process.env.PIN_PEPPER='isolated-test-pepper-0123456789-abcdefghijklmnopqrstuvwxyz';process.env.DATA_ENCRYPTION_KEY='22'.repeat(32);
const cryptoModule=new Module('crypto-test');cryptoModule._compile(ts.transpileModule(fs.readFileSync('lib/server/crypto.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,'crypto-test.cjs');const secure=cryptoModule.exports;
const backend=await testBackend();const year=new Date().getUTCFullYear();const db=backend.database;const head=randomUUID();await db.query('select yg_initialize_year($1)',[year]);await db.query('insert into users(id,display_name) values($1,$2)',[head,'부장테스트']);await db.query('insert into pin_credentials values($1,$2)',[head,await secure.hashPin('654321')]);await db.query("insert into student_verifications(user_id,school_year,student_number,status) values($1,$2,'20101','VERIFIED')",[head,year]);await db.query("insert into council_roles(user_id,school_year,role,is_head,can_deliver,starts_at,ends_at,granted_by) values($1,$2,'WELFARE_MANAGER',true,true,now(),now()+interval '1 year',$1)",[head,year]);
const userRow=(await db.query("select id from users where display_name='부장테스트'")).rows[0];
const env={...process.env,APP_ORIGIN:'http://127.0.0.1:3300',NEXT_PUBLIC_SUPABASE_URL:backend.url,NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'sb_publishable_local_test',SUPABASE_SECRET_KEY:'sb_secret_local_test',CRON_SECRET:'local-test-cron-only-abcdefghijklmnopqrstuvwxyz'};
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3300'],{env,stdio:['ignore','pipe','pipe']});
let browser;let debugPage;let errors=[];try{
 await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Next startup timeout')),20000);server.stdout.on('data',d=>{if(d.toString().includes('Ready')){clearTimeout(timeout);resolve()}});server.stderr.on('data',d=>{if(d.toString().includes('Error'))console.error(String(d))});server.on('exit',c=>reject(Error('Server stopped '+c)));});
 browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:process.env.CHROMIUM_ARGS_MODULE?(await import(process.env.CHROMIUM_ARGS_MODULE)).default.args.filter(a=>!['--disable-web-security','--single-process'].includes(a)):['--no-sandbox','--disable-dev-shm-usage']}: {})});
 const context=await browser.newContext({viewport:{width:390,height:844}});const page=await context.newPage();debugPage=page;page.on('response',async r=>{if(r.status()>=400&&r.url().includes('/api/'))console.error(r.status(),await r.text().catch(()=>''))});page.on('pageerror',e=>errors.push(e.message));
 const png=await sharp({create:{width:10,height:10,channels:3,background:'#ffe777'}}).png().toBuffer();
 await page.goto(env.APP_ORIGIN+'/login');await page.getByRole('button',{name:'처음 이용하나요? 학생 가입'}).click();await page.getByLabel('이름',{exact:true}).fill('가입테스트');await page.getByLabel('학번',{exact:true}).fill('20202');await page.getByLabel('6자리 비밀번호').fill('123456');await page.getByLabel('학생증 사진',{exact:true}).setInputFiles({name:'test.png',mimeType:'image/png',buffer:png});await page.getByRole('checkbox').check();await page.getByRole('button',{name:'가입 신청',exact:true}).click();await page.getByText('학생증을 확인하고 있어요.',{exact:true}).waitFor();assert.equal(backend.objects.size,1);
 const student=(await db.query("select id from users where display_name='가입테스트'")).rows[0].id;
 const headContext=await browser.newContext({viewport:{width:1440,height:1080}}),hp=await headContext.newPage();await hp.goto(env.APP_ORIGIN+'/login');await hp.getByLabel('이름',{exact:true}).fill('부장테스트');await hp.getByLabel('학번',{exact:true}).fill('20101');await hp.getByLabel('6자리 비밀번호').fill('654321');await hp.getByRole('button',{name:'로그인',exact:true}).click();await hp.getByRole('heading',{name:'내 이용 내역'}).waitFor();await hp.getByRole('link',{name:'관리',exact:true}).first().click();await hp.getByRole('button',{name:'학생 인증',exact:true}).click();await hp.getByRole('button',{name:'학생증 확인',exact:true}).last().click();await hp.getByRole('button',{name:'가입 승인',exact:true}).click();await hp.getByText('확인할 학생증이 없어요.').waitFor();assert.equal(backend.objects.size,0);console.log('PASS browser signup, login, privileged approval, storage object deletion');
 assert.equal((await page.evaluate(async()=>await (await fetch('/api/state')).json())).user.id,student);await page.reload();await page.getByText('인증 완료',{exact:true}).waitFor();await page.getByRole('link',{name:'등록',exact:true}).last().click();await page.getByLabel('물품 사진').setInputFiles({name:'item.png',mimeType:'image/png',buffer:png});await page.getByLabel('물품명',{exact:true}).fill('검증 물품');await page.locator('select[name="place"]').selectOption('E센터 2층');await page.getByLabel('세부 위치 (선택)').fill('중앙계단 근처');await page.getByLabel('발견 날짜').fill(new Date().toISOString().slice(0,10));await page.getByRole('button',{name:'등록 요청',exact:true}).click();await page.getByRole('heading',{name:'등록 요청이 완료됐어요.'}).waitFor();
 await hp.reload();await hp.getByRole('button',{name:'분실물 등록 요청',exact:true}).click();await hp.getByRole('heading',{name:'검증 물품'}).waitFor();assert(await hp.getByRole('button',{name:'등록 승인',exact:true}).isDisabled());await hp.getByRole('button',{name:'실물 확인',exact:true}).click();await hp.getByLabel('내부 보관번호').fill('A-01');await hp.getByRole('checkbox',{name:'공개 사진에 개인정보가 없는지 확인했어요.'}).check();await hp.getByRole('button',{name:'등록 승인',exact:true}).click();await hp.getByText('확인할 등록 요청이 없어요.').waitFor();console.log('PASS browser physical receipt and publication');
 await page.getByRole('link',{name:'찾기',exact:true}).last().click();await page.waitForURL('**/items');await page.reload();await page.getByRole('heading',{name:'검증 물품'}).waitFor();await page.getByRole('link',{name:'찾아가기',exact:true}).click();await page.getByLabel('물건의 특징').fill('안쪽 별 모양 표시가 있어요');await page.getByRole('button',{name:'찾아가기 요청',exact:true}).click();await page.getByText('본인 물건인지 확인하고 있어요.').waitFor();
 await hp.reload();await hp.getByRole('button',{name:'찾아가기 요청',exact:true}).click();await hp.getByRole('button',{name:'승인',exact:true}).click();await hp.getByText('확인할 요청이 없어요.').waitFor();
 const t=new Date(Math.ceil((Date.now()+3600000)/600000)*600000).toISOString();await db.query('select yg_action($1,$2,$3)',[userRow.id,'AVAILABILITY',JSON.stringify({starts:t,ends:new Date(new Date(t).getTime()+600000).toISOString()})]);
 await page.reload();await page.locator('.pickup-code strong').waitFor();const code=await page.locator('.pickup-code strong').textContent();await page.locator('.claim-card .chips button').first().click();await page.locator('.claim-card select').selectOption('안전생활부실 앞');await page.getByRole('button',{name:'예약하기',exact:true}).click();await page.getByText('담당: 부장테스트',{exact:false}).waitFor();
 await hp.getByRole('link',{name:'내 담당 일정',exact:true}).click();await hp.waitForURL('**/staff');await hp.reload();await hp.getByLabel('학생이 제시한 수령번호').fill(code);await hp.getByRole('checkbox',{name:'실제 물건을 전달했어요.'}).check();await hp.getByRole('button',{name:'수령 완료',exact:true}).click();await hp.getByText('배정된 수령 일정이 없어요.').waitFor();await page.reload();await page.getByText('수령이 완료됐어요.',{exact:true}).waitFor();assert.equal(await page.locator('.pickup-code').count(),0);console.log('PASS browser claim, approval, booking, assigned handoff, one-time code invalidation');

 // Exercise the new admin UI using the same student account and common login.
 await hp.goto(env.APP_ORIGIN+'/admin');await hp.getByRole('button',{name:'관리자 관리',exact:true}).click();
 const member=hp.locator('form.panel').filter({has:hp.getByRole('heading',{name:'가입테스트 · 20202',exact:true})});
 await member.getByRole('button',{name:'권한 저장',exact:true}).click();await member.getByText('현재: 학생회 임원',{exact:true}).waitFor();
 await page.goto(env.APP_ORIGIN+'/admin');await page.getByRole('heading',{name:'관리',exact:true}).waitFor();await page.getByRole('button',{name:'수령 일정',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'학생 인증',exact:true}).count(),0);
 await member.getByRole('button',{name:'권한 해제',exact:true}).click();await member.getByRole('button',{name:'해제 확정',exact:true}).click();await member.getByText('현재: 학생',{exact:true}).waitFor();
 await page.goto(env.APP_ORIGIN+'/admin');await page.waitForURL('**/my');await page.getByRole('heading',{name:'내 이용 내역'}).waitFor();assert.equal(await page.getByRole('link',{name:'관리',exact:true}).count(),0);
 const forged=await page.evaluate(async()=>{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'ROLE',userId:'00000000-0000-0000-0000-000000000000',role:'SUPER_ADMIN'})});return r.status});assert.equal(forged,400);
 await hp.getByRole('button',{name:'분실물 직접 등록',exact:true}).click();await hp.getByLabel('물품 사진').setInputFiles({name:'direct.png',mimeType:'image/png',buffer:png});await hp.getByLabel('물품명',{exact:true}).fill('관리자 직접 접수');await hp.locator('select[name="place"]').selectOption('기타');await hp.getByLabel('발견한 장소를 입력해주세요.').fill('본관 뒤 벤치 근처');await hp.getByLabel('발견 날짜').fill(new Date().toISOString().slice(0,10));await hp.getByLabel('발견 시간 (선택)').fill('13:20');await hp.getByLabel('내부 보관번호').fill('DIRECT-02');await hp.getByRole('checkbox',{name:'실제 물건을 받았고 확인했어요.'}).check();await hp.getByRole('checkbox',{name:'공개 사진에 개인정보가 없는지 확인했어요.'}).check();await hp.getByRole('button',{name:'공식 목록에 등록',exact:true}).click();await hp.getByRole('heading',{name:'분실물이 등록됐어요.'}).waitFor();
 await page.goto(env.APP_ORIGIN+'/items');await page.getByRole('heading',{name:'관리자 직접 접수'}).waitFor();assert.equal((await page.locator('body').innerText()).includes('DIRECT-02'),false);
 console.log('PASS UI role addition/revocation, server URL/API denial after revoke, administrator direct registration visible to students.');
 await db.query("update storage.buckets set public=true where id='student-verifications'");
 const unavailable=await page.evaluate(async()=>{const r=await fetch('/api/state');return {status:r.status,body:await r.json()}});assert.equal(unavailable.status,503);assert.equal(unavailable.body.connected,false);
 const blockedWrite=await page.evaluate(async()=>{const r=await fetch('/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'READ'})});return r.status});assert.equal(blockedWrite,503);
 await db.query("update storage.buckets set public=false where id='student-verifications'");
 console.log('PASS unsafe/missing backend configuration fails closed in state and mutation APIs.');

 for(const route of ['/','/items','/submit','/my','/notifications']){await page.goto(env.APP_ORIGIN+route);await page.waitForLoadState('networkidle');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' mobile overflow');}
 for(const route of ['/admin','/staff']){await hp.setViewportSize({width:390,height:844});await hp.goto(env.APP_ORIGIN+route);await hp.waitForLoadState('networkidle');assert.equal(await hp.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route+' overflow');}
 assert.equal((await (await context.request.get(env.APP_ORIGIN+'/api/image?kind=verification&id='+randomUUID())).body()).length,0);
 const noCsrf=await context.request.post(env.APP_ORIGIN+'/api/action',{headers:{Origin:'https://other.example'},data:{type:'READ'}});assert.equal(noCsrf.status(),400);
 assert.deepEqual(errors,[]);console.log('PASS mobile routes and JavaScript errors, cross-origin mutation denied. Local DB/Storage adapter, not hosted Supabase.');
 fs.mkdirSync('test-results',{recursive:true});await page.goto(env.APP_ORIGIN);await page.waitForLoadState('networkidle');await page.screenshot({path:'test-results/mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1080});await page.screenshot({path:'test-results/desktop.png',fullPage:true});
}catch(e){if(debugPage)console.error('UI state:',await debugPage.locator('body').innerText().catch(()=>''));throw e;}finally{if(browser)await browser.close();server.kill();await backend.close();}
